version: '3.8'

services:
  vllm-server:
    image: vllm/vllm-openai:latest
    container_name: vllm-hint-server
    ports:
      - "8000:8000"
    environment:
      - MODEL_NAME=${VLLM_MODEL:-Qwen/Qwen2.5-Coder-7B-Instruct}
      - GPU_MEMORY_UTILIZATION=${VLLM_GPU_MEMORY_UTILIZATION:-0.9}
      - MAX_MODEL_LEN=${VLLM_MAX_MODEL_LEN:-4096}
      - TENSOR_PARALLEL_SIZE=${VLLM_TENSOR_PARALLEL_SIZE:-1}
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: >
      --model ${VLLM_MODEL:-Qwen/Qwen2.5-Coder-7B-Instruct}
      --host 0.0.0.0
      --port 8000
      --gpu-memory-utilization ${VLLM_GPU_MEMORY_UTILIZATION:-0.9}
      --max-model-len ${VLLM_MAX_MODEL_LEN:-4096}
      --tensor-parallel-size ${VLLM_TENSOR_PARALLEL_SIZE:-1}
      --trust-remote-code
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

  hint-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hint-gradio-app
    ports:
      - "7860:7860"
    environment:
      - VLLM_SERVER_URL=http://vllm-server:8000/v1
      - DEFAULT_TEMPERATURE=0.7
    volumes:
      - ./data:/app/data
      - ./evaluation:/app/evaluation
    depends_on:
      - vllm-server
    restart: unless-stopped
